### ISSUE TITLE
Xcode 8 support

### ISSUE THREAD

**Issue by billchanmagic** [goktugyil/QorumLogs#33]
Hello! Thanks your great job to make my coding life colourful. I am trying my project with Xcode 8 now. Is there any plan to support Xcode 8 with coloured logging?

**Comment by Esqarrouth** [comment]
Yes, but I prefer not to touch it until its out of beta and stable. It may also work without changing anything. Or since we have a couple of dependencies which can break with the update, we might need to wait for them to support it first. Of course if you want to work on this I can create an xcode8 branch

**Comment by epyxhub** [comment]
Hi there, 

I went and fixed all the Swift 3 bugs but it doesn't log anything. 

It would be great to get a working version, after all logging is only used in dev to get these new iOS 10 apps build right now.

**Comment by Esqarrouth** [comment]
Just created the new version with it. Also added emojis instead of colors because xcode8 removed xcode colors. This is a temporary solution until we can find out how to get colors back properly. There are hacks like unsigning xcode, I personally rather use xcode7 until 8 is stable.

Heres how to install it with cocoapods:

```
pod 'QorumLogs' #For Swift 3.0    
pod 'QorumLogs', :git => 'https://github.com/goktugyil/QorumLogs.git', :branch => 'Swift2.3' #For Swift 2.3    
pod 'QorumLogs', '~> 0.8' #For Swift 2.2  
```
