### ISSUE TITLE
Swift3.0 support

### ISSUE THREAD

**Issue by SteveJKing** [goktugyil/QorumLogs#36]
Hi,
I am very like this framework.But now out projects already converted to swift3.0 with Xcode8, so we can not use it.Can you make the framework to support swift3.0 or create a swift3.0 beta branch.
Thanks.

**Comment by sunfffd** [comment]
+1

**Comment by Esqarrouth** [comment]
Just created the new version with it. Also added emojis instead of colors because xcode8 removed xcode colors. This is a temporary solution until we can find out how to get colors back properly. There are hacks like unsigning xcode, I personally rather use xcode7 until 8 is stable.

Heres how to install it with cocoapods:

```
pod 'QorumLogs' #For Swift 3.0    
pod 'QorumLogs', :git => 'https://github.com/goktugyil/QorumLogs.git', :branch => 'Swift2.3' #For Swift 2.3    
pod 'QorumLogs', '~> 0.8' #For Swift 2.2  
```
